name: Lint

on: [push, pull_request]

env:
  RUFF_OUTPUT_FORMAT: github

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gardenlinux/python-gardenlinux-lib/.github/actions/setup@main
      - run: make lint
